### ISSUE TITLE
Integration with view controller other than UIViewController

### ISSUE THREAD

**Issue by mierzynskim** [akane/Akane#16]
Hello,
I'm planning to integrate Akane into my project. I've got one question. Is it possible to integrate ComponentViewController with eg. UITableViewController or UICollectionViewController? I didn't find any example how to do it.
Thanks in advance

**Comment by pjechris** [comment]
`ComponentViewController` has been replaced by `ComponentController` protocol in 0.17.
So you should be able to use it alongside `UITableViewController`. That said, I never tried it so would be very interested to hear if it really works 😉

**Comment by pjechris** [comment]
@mierzynskim Did you succeed to integrate with `UITableViewController` or do you need some help?
