### ISSUE TITLE
Variable used within its own initial value

### ISSUE THREAD

**Issue by bradyrichmond** [akane/Akane#20]
Trying to use this on a new application and getting a few build errors.

**Variable used within its own initial value**
`let type = type(of: view).componentControllerClass() as! UIViewController.Type`

and

**Cannot assign value of type '() -> ()' to type '((Void) -> Void)?'**
` updatable.onRender = { [weak collectionView] in
                    if let collectionView = collectionView {
                        collectionView.update(.cell, atIndexPath: indexPath)
                    }
                }`

Not sure if this is something local or not.

**Comment by pjechris** [comment]
Swift4 support has just been merged into master.
You can use pinpoint to master head into your Podfile into it is tagged.

**Comment by bradyrichmond** [comment]
Thanks @pjechris!  Builds successfully now.
